### ISSUE TITLE
Add ntpd

### ISSUE THREAD

**Issue by runlevel5** [chimera-linux/cports#129]
Why? Because I would like to get my system's time in synced. I don't have the full context why there is no NTPd in this distro so please let me on in.

There are a number of NTP implementations for example ntpd, chrony, NTPsec, OpenNTP, etc. IMHO the distro should opt in a default package on the behalf of users that could meet BSD licensing, integration (for example with GNOME) and security. Please treat this github issue as the placeholder for further discussion.

**Comment by q66** [comment]
i don't see how an ntpd is anyhow special as opposed to any other software that is currently missing and why that needs a ticket

the distro is clearly not ready for daily driving, packages very little software outside of what is absolutely necessary, and the website and other places state that multiple times

**Comment by runlevel5** [comment]
@q66 I meant no ill intention. Just trying to help out with the development.

**Comment by q66** [comment]
there are obviously plans to add some kind of time synchronization daemon, but there are really more important things to do than adding more software, and if i had to deal with every request people make i wouldn't be able to do anything else

fwiw integration with gnome is going to be tricky because the g-s-d plugin relies on systemd-timedated (but maybe a standalone implementation of the dáme d-bus interface could be made)
