### ISSUE TITLE
question: allocator

### ISSUE THREAD

**Issue by dkwo** [chimera-linux/cports#140]
What was the reason for choosing the Scudo allocator?
How hard would it be to replace it with hardened-malloc https://github.com/GrapheneOS/hardened_malloc ?
Thanks.

**Comment by q66** [comment]
1. because it performs well
2. hard

**Comment by Jimbassfisher** [comment]
@q66 is scudo more secure and performant than malloc-ng?

**Comment by q66** [comment]
it's probably a bit less secure than malloc-ng, because it by design cannot provide the same guarantees, but it shouldn't be by much, and the performance is *much* better in anything that is threaded (up to 200x better depending on the workload)

e.g. it boosts overall lld LTO link times by 3x, helps hugely when it comes to interactivity in anything using rust (e.g. firefox), java, etc

mallocng keeps a global lock so it will never scale past 1 thread and will bottleneck various workloads because of that (but it's also a design intention, as a global lock is the only way to have guaranteed global consistency)

i don't consider the benefit big enough in non-paranoid setups, scudo is already a best-effort hardened allocator and that's gotta be good enough

**Comment by q66** [comment]
the allocator performance is the number 1 reason people say musl performs worse than glibc (the other reasons are mostly fewer optimized algorithm implementations for various libc functions, as musl relies on generic implementations primarily except in some specific cases, but the difference there tends to be within single digit percent and not particularly visible in most practical things)

scudo is an obvious choice because it's modular and generally unassuming, which makes it easy to integrate, e.g. most out-of-libc allocators tend to rely on ELF TLS directly which is a no go in musl (because the libc is also the dynamic linker and the dynamic linker code itself allocates, but also does not handle ELF TLS), scudo makes it easy because we can implement a custom TSD registry instead which stores its thread-specific pointer directly within the pthread internal structure, then plug that into the allocator and we're done

**Comment by Jimbassfisher** [comment]
Thanks for the clarification, I can definetly see that the tradeoff in security is worth the "lost" security.
