### ISSUE TITLE
Unable to perform disk operations (nautilus mount, gnome-disks actions)

### ISSUE THREAD

**Issue by JamiKettunen** [chimera-linux/cports#217]
Example errors of trying to resize a partition in `gnome-disks` and mount something via UDisks2 (in `nautilus`):
![image](https://github.com/chimera-linux/cports/assets/47358222/8969fe15-063e-46f2-a69c-2c2ad4dbb370)
![image](https://github.com/chimera-linux/cports/assets/47358222/eff9d821-3e6e-4b61-934f-7633ab86cfe5)

My user is in the groups `wheel disk adm cdrom storage plugdev users $USER` fwiw.

A crappy workaround for this could be https://gist.github.com/grawity/3886114#file-udisks1-wheel-is-god-js but doing `\.udisks` instead of `\.udisks\.` (to allow it to match `udisks2` as well)
```js
/* Copy this to /etc/polkit-1/rules.d/always-allow-wheel.rules */

polkit.addRule(function(action, subject) {
    if (/^org\.freedesktop\.udisks/.test(action.id) && subject.isInGroup("wheel"))
    {
        return polkit.Result.YES;
    }
});
```
Finally some quotes from @q66:
> funnily i can use `udisksctl` from command line without any trouble
> i think the issue is something with gvfs, though maybe not, who knows

**Comment by q66** [comment]
the reason this happens is that gio/gvfs udisks operations are executed through session bus, which runs in turnstile; turnstile is currently not set up to register its session with logind, which means user services currently run completely outside of logind's knowledge - and the way polkit authorizes this works by checking if the process asking for it is in a local, active session - and as it is, it will not find any session, so it will deny it

the fix is to have a persistent PAM session in turnstile, and then register it with pam_elogind so that elogind is aware of it for the duration of the service manager's existence; we will also need to make sure pam_turnstile executes after pam_elogind in the system login path and passes the XDG_SEAT (if it exists) and export it to the environment turnstile-side before setting up the user-service-manager PAM session, otherwise it will be seat-less and polkit won't consider it local (so it will still deny it)

i'm currently reworking the turnstile session code for this, without that it won't go anywhere
