### ISSUE TITLE
[package request] krb5-devel

### ISSUE THREAD

**Issue by whypet** [chimera-linux/cports#2744]
Currently the only implementation of Kerberos available is [heimdal-devel](https://pkgs.chimera-linux.org/package/current/main/x86_64/heimdal-devel), however some software depends on the [MIT Kerberos](https://web.mit.edu/kerberos/) implementation instead and fails to build, which conflicts with Heimdal. This would allow VSCode to be built on Chimera Linux (and run using the [same patches](https://git.alpinelinux.org/aports/tree/testing/code-oss?h=master) that Alpine's code-oss package employs).

**Comment by nekopsykose** [comment]
> This would allow VSCode to be built on Chimera Linux 

you would still need electron which nobody has plans to add (for good reason), so not really

**Comment by q66** [comment]
heimdal implements the same api as mit kerberos so it's unlikely to be added and is the least of your worries when packaging vscode

**Comment by whypet** [comment]
Thanks for clarifying, I didn't realize Electron wasn't available at all (as I got used to running it in Flatpak which makes no sense to run VSCode in). May I know the reasoning for not packaging it, in the case that anyone would be willing to work on it? I wouldn't mind contributing if it's not there because there isn't any need for it.

**Comment by nekopsykose** [comment]
part of the reason is that it would only be useful for vscode (since running an ide in flatpak doesn't work unless it's something like gnome builder that uses container toolchains for everything), and for pretty much every other app it would be actively bad to package them

currently nobody does that because there is no electron (so of course), but once it's there you end up with whatever random awful thing made in electron today came out that someone shows up to package (i look at void-packages every so often for fun), and i saw exactly that happen when i packaged electron in alpine for vscode; everyone suddenly wanted to add their one super cool app that uses electron and now you have 50 awful templates that all take (usually) way too long to build and offer no benefits over just using the flatpak anyway

the other part is that it's annoying to actually package and maintain and takes forever to build and resources are limited enough as is; the only people that can actually maintain electron in a distro are the same people that maintain chromium (so, practically me), since it's mostly the same thing (in the sense of maintaining it specifically), minus being a few versions behind, plus some extra electron-specific stuff, plus finding a place to host tarballs, plus generating them (like in alpine), etc

so.. i'd have to do it, and then also i'd prefer if we had a policy of 'no electron apps except vscode, haha (unless there was actually a good reason for it)', and i guess that would be ok, but these days i'm not super interested in working on stuff i never use and that takes a ton of hours of me doing it for no benefit to myself :)

**Comment by whypet** [comment]
I honestly wasn't aware of how much work needs to be done and I don't think it's worth all the effort to maintain Electron, so thanks for your insight. I personally don't really have any need for Electron (or, MIT Kerberos) other than for running VSCode, I'll close this issue.
