### ISSUE TITLE
perhaps apk update only at start of bulk

### ISSUE THREAD

**Issue by nekopsykose** [chimera-linux/cports#2950]
currently in a given bulk-pkg the

```
updating software in /home/runner/work/cports/cports/bldroot.9pp15qii container...
```

runs for every single package, but it could probably run just once at the start instead and be effectively almost the same

mostly because otherwise every pkg step involves 4 sequential http fetches for the 4 indexes (main,user + debug) and in ci that takes longer than it has to (like 3s total across the ocean)

the same goes locally too, technically, where before e33551cd9b57a604792e7becbd80c3076a9ffe38 it was nice that it didn't actually update every time- the main issue is just that apk doesn't stale apkindex's correctly it seems. but it would be nice if it only updated for things over a minute old and up to a minute skipped the fetches..

**Comment by q66** [comment]
not really viable as apk needs to have the current upstream repo status in order to properly install dependencies (esp. for local builds where the remote repo may have changed after a long build of a package in a bulk batch) and also it's a pain to implement regardless due to chroot.update only updating repos relevant to the current build and those may differ between packages if they're present in different categories
