### ISSUE TITLE
harfbuzz outdated ICU dependency breaking build

### ISSUE THREAD

**Issue by doskel** [chimera-linux/cports#3121]
When building `main/evolution` with a binary bootstrapped container, it fails with dependency errors.
icu-libs is required to be version 76.1 by libxml2, but required to be 75.1 by harfbuzz. I can't tell where harfbuzz is requesting this dependency, but it's evidently an issue somewhere.

**Comment by nekopsykose** [comment]
that is because the repositories haven't actually built and updated icu yet, so when building main/evolution it first builds the new icu for you and then also rebuilds xml, but fails to also rebuild harfbuzz due to it being a transitive dep somewhere

the actual issue will be fixed when the repos upload, the cbuild missing an automatic local rebuild for transitive deps is separate

**Comment by doskel** [comment]
ah yeah, building harfbuzz manually did the trick. thanks for the help, sorry for the trouble.
