### ISSUE TITLE
remove extra dependencies of plasma-desktop

### ISSUE THREAD

**Issue by BarryLhm** [chimera-linux/cports#3292]
I think some kde applications (such as konqueror and kdenlive) are optional for plasma desktop so shouldn't be dependencies of plasma-desktop package.
That makes them unremovable.

plasma-desktop includes necessary files to run plasma, so it's the core of plasma and shouldn't be a meta package at the same time.

I suggest creating a standalone meta package including those extra kde apps so they can be removed.

**Comment by JamiKettunen** [comment]
`apk add '!plasma-desktop-meta'` and craft your own desktop experience without anything you don't want by explicitly adding them back.

in a way separating the dependency metadata makes sense because you wouldn't have to rebuild the whole plasma-desktop package but that doesn't realistically happen often anymore and I'm not sure if @q66 had some other idea what to do with this instead, so the maskable `-meta` packages remain for now

**Comment by BarryLhm** [comment]
there's still x server to be installed. why not drop xorg session or move it into another meta package?

**Comment by JamiKettunen** [comment]
I don't think that makes any sense atm considering even SDDM itself cannot properly run under Wayland, that's likely what's pulling in Xorg on your system anyway.

if you can figure out making sddm run on wayland feel free to contribute, it was specifically excluded because it was utterly broken previously and either couldn't even properly run the wayland compositor or other similar problem.

**Comment by BarryLhm** [comment]
but how does sddm run under wayland on fedora? is that a modified version?

**Comment by BarryLhm** [comment]
and plasma-desktop itself can run without X server. so please make xorg a dependency of sddm instead of plasma-desktop.

**Comment by JamiKettunen** [comment]
have you even tried to figure out why you have Xorg installed? start from `apk info --rdepends xserver-xorg-core` and go down the chain. all explicit mentions related to it in https://github.com/chimera-linux/cports/blob/master/main/plasma-desktop/template.py that can be are already under `plasma-desktop-x11-meta` which you wouldn't have it you did `apk add '!plasma-desktop-meta'` from before.

fedora is largely irrelevant if sddm cannot be run on wayland under chimera, sometimes they also very extensively patch packages [like seen with grub](https://src.fedoraproject.org/rpms/grub2/tree/rawhide). anyway try it here and see. https://invent.kde.org/plasma/plasma-workspace/-/blob/master/sddm-wayland-session/plasma-wayland.conf which even installed by default due to https://invent.kde.org/plasma/plasma-workspace/-/blob/v6.2.4/CMakeLists.txt#L14 is required in `/etc/sddm.conf.d` and maybe others, I'm sure you can dig up the details if you really want to get rid of xorg this bad while having sddm installed.

**Comment by BarryLhm** [comment]
i don't have sddm installed and i remember that xorg is installed because of adding plasma-desktop with all plasma-desktop-*meta packages masked before.

**Comment by BarryLhm** [comment]
i will check this further tomorrow.

**Comment by BarryLhm** [comment]
thanks for your patience
