### ISSUE TITLE
Add API for cbuild

### ISSUE THREAD

**Issue by q66** [chimera-linux/cports#40]
The system should provide some kind of API that should be usable from external programs. There are a few approaches we could take:

1) Python API?
2) Some kind of command interface for usage from shell scripts and so on?
3) A `cbuild` server + some kind of API over a protocol?
3) All of these?

**Comment by bjornstromberg** [comment]
some thoughts on this

i would probably use a publish/subscribe message system over websocket due to #134 that gives the possibility to distribute the load over multiple nodes.. 

since this is a green field distro 'we' should try to support parallelism as much as possible, de-centralization is not a bad thing especially now that arm64 singleboard computers gives possibilities to build small noded clusters without to much cost per node.

with this approach creating a cli or python-api interface is just a wrapper on top of the websocket on localhost it would also support containerized docker solutions.

**Comment by q66** [comment]
not planned for now
