### ISSUE TITLE
Separation of non-free packages

### ISSUE THREAD

**Issue by blacklightpy** [chimera-linux/cports#875]
Hello! I liked this project, being a Void Linux user. However, I noticed that currently many non-free packages like `firmware-linux-nvidia` and `ucode*` are included in the `main` repository. Will this be separated? I recommend it, because this is discouraging me from using this over Void.

But I saw a `non-free` folder in this repo, so maybe it's going to be added later?

**Comment by nekopsykose** [comment]
>However, I noticed that currently many non-free packages like firmware-linux-nvidia and ucode* are included in the main repository. Will this be separated? I recommend it, because this is discouraging me from using this over Void.

void does the same? they are also in the main repository, and they just come from https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git

**Comment by q66** [comment]
no

**Comment by nekopsykose** [comment]
(the only thing void seems to put in nonfree repo but we put in main is ucode-intel)

**Comment by blacklightpy** [comment]
> void does the same? they are also in the main repository, and they just come from https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git

@nekopsykose Yes, but they are non-free packages, so void just separates them out. But the kernel doesn't seem to be linux-libre by default. 

> as psykose said
> 
> it's not really possible to separate them regardless

@q66 I made a mistake about the firmware package, it was `nvidia`, the userland driver rather than `linux-firmware-nvidia`. 

It's not just those packages though, there could be something like, Discord for example (although available in flatpak). Some other example would be `chromium-widevine`, `1password-cli`, etc.

On the firmware side, there are some like the `Broadcom Wireless DKMS module` and so on. But largely, CLI apps seem to be open source and the GUI apps can just be Flatpak so you can save packaging time?

Or maybe let the users download the non-free software from the respective websites?

**Comment by q66** [comment]
chimera doesn't support any of that software (discord, widevine etc) anyway because they don't provide musl builds

gui or cli has nothing to do with it, and we'll package whatever is packageable doesn't violate the rules, flatpak has significantly poorer platform support than chimera does and flatpak apps don't get the same level of compiler security hardening

**Comment by q66** [comment]
it makes a difference, because there is no libgcc_s.so.1 (instead there is libunwind.so.1 and the other symbols are in libclang_rt.builtins.a and statically linked), additionally there is no libstdc++.so.6 (instead there is libc++.so.1) so it's fundamentally incompatible without compat shims

**Comment by q66** [comment]
in any case we're not going to have a separate non-free repo, if it's buildable and redistributable and otherwise meets the requirements it goes in main or contrib

there isn't enough software that would qualify for such repo and still meet the rules, and for the rest, if somebody doesn't want them they don't have to install them

**Comment by blacklightpy** [comment]
Yeah it makes sense. I expected there to be more software, but there really isn't much.
